// Where lab report files live. Everything else in the lab module only calls
// saveReport / openReport / deleteReport, so the storage can be swapped (for
// example to the hospital's Google Drive) by adding one provider here.
//
//   REPORT_STORAGE=cloudinary  private files in Cloudinary (default when Cloudinary is configured)
//   REPORT_STORAGE=local       files on this server's disk (REPORT_LOCAL_DIR). Only for local
//                              development or a server with a permanent disk: on Render/Vercel
//                              the disk is wiped on every restart and reports would be lost.
//
// Files are never given out as public links. The browser gets a short-lived link to
// our own API, which checks who is asking and then streams the file (see labController).
import fs from "fs";
import path from "path";
import crypto from "crypto";
import { Readable } from "stream";
import { v2 as cloudinary } from "cloudinary";

const isCloudinaryConfigured = () =>
  Boolean(process.env.CLOUDINARY_NAME && process.env.CLOUDINARY_API_KEY && process.env.CLOUDINARY_SECRET_KEY);

export const reportStorageName = () => {
  const wanted = (process.env.REPORT_STORAGE || "").toLowerCase();
  if (wanted === "local") return "local";
  if (wanted === "cloudinary" || !wanted) return isCloudinaryConfigured() ? "cloudinary" : "local";
  return "local";
};

const localDir = () => path.resolve(process.env.REPORT_LOCAL_DIR || "uploads/lab-reports");

const providers = {
  local: {
    async save(filePath, { extension }) {
      const dir = localDir();
      await fs.promises.mkdir(dir, { recursive: true });
      const key = `${crypto.randomUUID()}${extension}`;
      await fs.promises.copyFile(filePath, path.join(dir, key));
      return key;
    },
    async open(key) {
      // Keys are generated by us; refuse anything that looks like a path
      if (!/^[\w-]+\.[a-z0-9]+$/i.test(key)) throw new Error("Invalid file key");
      return fs.createReadStream(path.join(localDir(), key));
    },
    async remove(key) {
      if (!/^[\w-]+\.[a-z0-9]+$/i.test(key)) return;
      await fs.promises.unlink(path.join(localDir(), key)).catch(() => {});
    },
  },

  cloudinary: {
    // "raw" + "private": stored as an ordinary file, never reachable by a public URL
    async save(filePath, { extension }) {
      const result = await cloudinary.uploader.upload(filePath, {
        resource_type: "raw",
        type: "private",
        folder: "lab-reports",
        public_id: `${crypto.randomUUID()}${extension}`,
        overwrite: false,
      });
      return result.public_id;
    },
    async open(key) {
      // Signed download through Cloudinary's API, valid for a minute, fetched by the server
      const url = cloudinary.utils.private_download_url(key, "", {
        resource_type: "raw",
        type: "private",
        expires_at: Math.floor(Date.now() / 1000) + 60,
      });
      const response = await fetch(url);
      if (!response.ok || !response.body) throw new Error(`Report download failed (HTTP ${response.status})`);
      return Readable.fromWeb(response.body);
    },
    async remove(key) {
      await cloudinary.uploader.destroy(key, { resource_type: "raw", type: "private" }).catch(() => {});
    },
  },
};

const provider = (name) => {
  const p = providers[name];
  if (!p) throw new Error(`Report storage "${name}" is not available`);
  return p;
};

// Save an uploaded file (multer temp path). Returns what to keep on the order.
export const saveReport = async (file) => {
  const storage = reportStorageName();
  // From the file type (the upload only allows PDF/JPG/PNG/WebP), not the name, so keys stay valid
  const extension = mimeExtension(file.mimetype) || ".bin";
  const key = await provider(storage).save(file.path, { extension });
  return {
    storage,
    key,
    fileName: (file.originalname || `report${extension}`).slice(0, 120),
    mimeType: file.mimetype,
    size: file.size,
  };
};

// A readable stream of a stored report (ref: an entry of order.reports)
export const openReport = (ref) => provider(ref.storage).open(ref.key);

export const deleteReport = (ref) => provider(ref.storage).remove(ref.key);

const mimeExtension = (mime) =>
  ({ "application/pdf": ".pdf", "image/jpeg": ".jpg", "image/png": ".png", "image/webp": ".webp" })[mime] || "";
